"""Models living in each institution's `tenant_<slug>` schema.

Importing this package registers every implemented model (Phase 1 org/RBAC/
audit, plus the Phase 2/3 course catalog, OBE outcome hierarchy, mappings,
and accreditation framework catalogue, plus course delivery/grading and
assessment definition) on `TenantBase`'s metadata, which is what
`alembic/tenant/env.py` autogenerates against and what
`app.services.tenancy.provision_tenant` creates tables from.
"""

from app.models.tenant.accreditation import (
    AccreditationBody,
    AccreditationFramework,
    EngineeringActivity,
    FrameworkPO,
    KnowledgeProfile,
    ProblemAttribute,
)
from app.models.tenant.assessments import (
    Assessment,
    AssessmentDocument,
    AssessmentQuestion,
    AssessmentQuestionProgramOutcomeMapping,
    AssessmentType,
    AttainmentSnapshot,
    CourseAttainmentConfig,
    GradeSubmission,
    ProgramAttainmentConfig,
    Question,
    QuestionBloomMapping,
    QuestionCourseOutcomeMapping,
    Rubric,
    RubricCriterion,
    RubricLevel,
    StudentMark,
)
from app.models.tenant.audit import AuditLog, AuditLogSettings, Notification
from app.models.tenant.change_requests import CourseChangeRequest
from app.models.tenant.course_files import (
    CourseFileRequirement,
    CourseFileSubmission,
    CourseFileType,
)
from app.models.tenant.course_type_config import CourseTypeSectionConfig
from app.models.tenant.courses import (
    Course,
    CourseOffering,
    CourseSection,
    CourseType,
    CourseVersion,
    FacultyAssignment,
    GradingBand,
    GradingPolicy,
    StudentEnrollment,
)
from app.models.tenant.curriculum_feedback import CurriculumFeedback
from app.models.tenant.identity import (
    FacultyProfile,
    Permission,
    Role,
    RolePermission,
    StudentProfile,
    User,
    UserRole,
)
from app.models.tenant.mappings import (
    CourseOutcomePIMapping,
    CourseOutcomePOMapping,
    MappingScale,
    MappingScaleLevel,
    ProgramOutcomeEngineeringActivityMapping,
    ProgramOutcomeKnowledgeProfileMapping,
    ProgramOutcomePEOMapping,
    ProgramOutcomeProblemAttributeMapping,
)
from app.models.tenant.obe import (
    PEO,
    BloomLevel,
    CourseOutcome,
    ImprovementPlan,
    InstitutionalMission,
    InstitutionalVision,
    InstitutionalVisionProgramVisionMapping,
    PeoVisionMapping,
    PerformanceIndicator,
    ProgramMission,
    ProgramOutcome,
    ProgramVision,
)
from app.models.tenant.org import (
    AcademicTerm,
    AcademicYear,
    Campus,
    Cohort,
    Department,
    Program,
    ProgramVersion,
    School,
    TermEffectiveCurriculum,
)
from app.models.tenant.raw_data import RawDataChangeRequest
from app.models.tenant.term_commit import TermCommit

__all__ = [
    "PEO",
    "AcademicTerm",
    "AcademicYear",
    "AccreditationBody",
    "AccreditationFramework",
    "Assessment",
    "AssessmentDocument",
    "AssessmentQuestion",
    "AssessmentQuestionProgramOutcomeMapping",
    "AssessmentType",
    "AttainmentSnapshot",
    "AuditLog",
    "AuditLogSettings",
    "BloomLevel",
    "Campus",
    "Cohort",
    "Course",
    "CourseAttainmentConfig",
    "CourseChangeRequest",
    "CourseFileRequirement",
    "CourseFileSubmission",
    "CourseFileType",
    "CourseOffering",
    "CourseOutcome",
    "CourseOutcomePIMapping",
    "CourseOutcomePOMapping",
    "CourseSection",
    "CourseType",
    "CourseTypeSectionConfig",
    "CourseVersion",
    "CurriculumFeedback",
    "Department",
    "EngineeringActivity",
    "FacultyAssignment",
    "FacultyProfile",
    "FrameworkPO",
    "GradeSubmission",
    "GradingBand",
    "GradingPolicy",
    "ImprovementPlan",
    "InstitutionalMission",
    "InstitutionalVision",
    "InstitutionalVisionProgramVisionMapping",
    "KnowledgeProfile",
    "MappingScale",
    "MappingScaleLevel",
    "Notification",
    "PeoVisionMapping",
    "Permission",
    "PerformanceIndicator",
    "ProblemAttribute",
    "Program",
    "ProgramAttainmentConfig",
    "ProgramMission",
    "ProgramOutcome",
    "ProgramOutcomeEngineeringActivityMapping",
    "ProgramOutcomeKnowledgeProfileMapping",
    "ProgramOutcomePEOMapping",
    "ProgramOutcomeProblemAttributeMapping",
    "ProgramVersion",
    "ProgramVision",
    "Question",
    "QuestionBloomMapping",
    "QuestionCourseOutcomeMapping",
    "RawDataChangeRequest",
    "Role",
    "RolePermission",
    "Rubric",
    "RubricCriterion",
    "RubricLevel",
    "School",
    "StudentEnrollment",
    "StudentMark",
    "StudentProfile",
    "TermCommit",
    "TermEffectiveCurriculum",
    "User",
    "UserRole",
]
